USE [master]
GO
/****** Object:  Database [RegistrationCRUD]    Script Date: 27 Apr 2025 09:54:25 PM ******/
CREATE DATABASE [RegistrationCRUD]
 CONTAINMENT = NONE
 ON  PRIMARY 
( NAME = N'RegistrationCRUD', FILENAME = N'E:\SQL\DataBase\RegistrationCRUD.mdf' , SIZE = 8192KB , MAXSIZE = UNLIMITED, FILEGROWTH = 65536KB )
 LOG ON 
( NAME = N'RegistrationCRUD_log', FILENAME = N'E:\SQL\DataBase\RegistrationCRUD_log.ldf' , SIZE = 8192KB , MAXSIZE = 2048GB , FILEGROWTH = 65536KB )
 WITH CATALOG_COLLATION = DATABASE_DEFAULT
GO
ALTER DATABASE [RegistrationCRUD] SET COMPATIBILITY_LEVEL = 150
GO
IF (1 = FULLTEXTSERVICEPROPERTY('IsFullTextInstalled'))
begin
EXEC [RegistrationCRUD].[dbo].[sp_fulltext_database] @action = 'enable'
end
GO
ALTER DATABASE [RegistrationCRUD] SET ANSI_NULL_DEFAULT OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET ANSI_NULLS OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET ANSI_PADDING OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET ANSI_WARNINGS OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET ARITHABORT OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET AUTO_CLOSE OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET AUTO_SHRINK OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET AUTO_UPDATE_STATISTICS ON 
GO
ALTER DATABASE [RegistrationCRUD] SET CURSOR_CLOSE_ON_COMMIT OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET CURSOR_DEFAULT  GLOBAL 
GO
ALTER DATABASE [RegistrationCRUD] SET CONCAT_NULL_YIELDS_NULL OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET NUMERIC_ROUNDABORT OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET QUOTED_IDENTIFIER OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET RECURSIVE_TRIGGERS OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET  DISABLE_BROKER 
GO
ALTER DATABASE [RegistrationCRUD] SET AUTO_UPDATE_STATISTICS_ASYNC OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET DATE_CORRELATION_OPTIMIZATION OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET TRUSTWORTHY OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET ALLOW_SNAPSHOT_ISOLATION OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET PARAMETERIZATION SIMPLE 
GO
ALTER DATABASE [RegistrationCRUD] SET READ_COMMITTED_SNAPSHOT OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET HONOR_BROKER_PRIORITY OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET RECOVERY SIMPLE 
GO
ALTER DATABASE [RegistrationCRUD] SET  MULTI_USER 
GO
ALTER DATABASE [RegistrationCRUD] SET PAGE_VERIFY CHECKSUM  
GO
ALTER DATABASE [RegistrationCRUD] SET DB_CHAINING OFF 
GO
ALTER DATABASE [RegistrationCRUD] SET FILESTREAM( NON_TRANSACTED_ACCESS = OFF ) 
GO
ALTER DATABASE [RegistrationCRUD] SET TARGET_RECOVERY_TIME = 60 SECONDS 
GO
ALTER DATABASE [RegistrationCRUD] SET DELAYED_DURABILITY = DISABLED 
GO
ALTER DATABASE [RegistrationCRUD] SET ACCELERATED_DATABASE_RECOVERY = OFF  
GO
ALTER DATABASE [RegistrationCRUD] SET QUERY_STORE = OFF
GO
USE [RegistrationCRUD]
GO
/****** Object:  Table [dbo].[City]    Script Date: 27 Apr 2025 09:54:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[City](
	[CityId] [int] IDENTITY(1,1) NOT NULL,
	[CityName] [varchar](50) NULL,
	[StateId] [int] NULL,
 CONSTRAINT [PK_City] PRIMARY KEY CLUSTERED 
(
	[CityId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[State]    Script Date: 27 Apr 2025 09:54:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[State](
	[StateID] [int] IDENTITY(1,1) NOT NULL,
	[StateName] [varchar](50) NULL,
 CONSTRAINT [PK_State] PRIMARY KEY CLUSTERED 
(
	[StateID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY]
GO
/****** Object:  Table [dbo].[UserDetails]    Script Date: 27 Apr 2025 09:54:25 PM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[UserDetails](
	[userID] [int] IDENTITY(1,1) NOT NULL,
	[Name] [varchar](50) NULL,
	[Gender] [varchar](50) NULL,
	[DOB] [datetime] NULL,
	[Email] [varchar](150) NULL,
	[Contact] [varchar](10) NULL,
	[Phone] [varchar](10) NULL,
	[State] [int] NULL,
	[City] [int] NULL,
	[Hobbies] [varchar](100) NULL,
	[PhotoPath] [varchar](max) NULL,
 CONSTRAINT [PK_UserDetails] PRIMARY KEY CLUSTERED 
(
	[userID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON, OPTIMIZE_FOR_SEQUENTIAL_KEY = OFF) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
GO
USE [master]
GO
ALTER DATABASE [RegistrationCRUD] SET  READ_WRITE 
GO
